language: ruby
rvm:
  - 2.6.5

install:
  - bundle install --jobs 3 --retry 3
  - nvm install 10
  - node -v
  - npm i -g yarn
  - yarn

script:
  - bundle exec rake db:create:all
  - bundle exec rake db:migrate RAILS_ENV=test
  - ruby -Itest test/models/aluno_test.rb
  - ruby -Itest test/models/professor_test.rb
  - bundle exec rails webpacker:compile
  - ruby -S bundle exec cucumber --profile default

services:
  - postgresql
